---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ceriumos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - yaru-theme
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: gnome-extensions
    install:
      # Combines top bar and dash into a single panel, mimicking the ChromeOS shelf.
      # Confirmed maintained and supports recent GNOME versions.
      - dash-to-panel@jderose9.github.com
      # Provides a configurable app menu similar to Manjaro's. Confirmed maintained
      # and supports recent GNOME versions.
      - arcmenu@arcmenu.com
      # Provides granular control over the GNOME Shell UI to hide unwanted elements.
      # Confirmed maintained and supports recent GNOME versions.
      - just-perfection-desktop@just-perfection
      # Allows loading of custom shell themes, essential for a custom brand look.
      # Confirmed maintained and available from extensions.gnome.org.
      - user-theme@gnome-shell-extensions.gcampax.github.com
      # Provides support for application indicator icons in the system tray,
      # which is a feature many users expect. Confirmed maintained and available.
      - appindicator@gnome-shell.extensions.gnome.org
      # THE END
customization:
  # Reference the files using the correct paths within your repo structure
  files:
    # Source path points to where the file is in your repository
    - source: ./files/scripts/gnome_config.sh
      # Destination is where it will be placed in the final OS image
      destination: /usr/bin/gnome_config.sh
      mode: 755
    - source: ./files/scripts/flatpak_config.sh
      destination: /usr/bin/flatpak_config.sh
      mode: 755

  # Run the scripts during the build process
  # The path here is the destination path within the OS image
  scripts:
    - /usr/bin/gnome_config.sh
    - /usr/bin/flatpak_config.sh

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
